-- Seed pipeline templates — run after schema.sql (idempotent upserts)
-- Canonical definitions: backend/app/templates/*.py

insert into pipeline_templates (
    id, name, description, icon, category, default_task,
    fields, extraction_instructions, rules, output_format,
    suggested_steps, example_output_fields, sort_order, is_active
) values
(
    'invoice',
    'Invoice Parser',
    'Extract vendor, amounts, dates, line items from invoices.',
    'receipt',
    'finance',
    'Extract structured data from these invoices. Pull header fields and all line items. Normalize amounts to numbers (no currency symbols). Dates in ISO format (YYYY-MM-DD).',
    '["invoice_number","vendor_name","vendor_address","invoice_date","due_date","subtotal","tax_amount","total_amount","currency","payment_terms","line_items"]'::jsonb,
    'For line_items, return an array of objects with keys: description, quantity, unit_price, amount. If tax is not explicitly stated, set tax_amount to null. payment_terms examples: ''Net 30'', ''Due on receipt'', ''Net 60''. If multiple currencies appear, use the one on the total line.',
    '[{"field":"total_amount","operator":"gt","value":50000,"flag_name":"high_value_invoice"},{"field":"due_date","operator":"lt","value":"today","flag_name":"overdue"}]'::jsonb,
    'csv',
    '["processor.ocr","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["invoice_number","vendor_name","vendor_address","invoice_date","due_date","subtotal","tax_amount","total_amount","currency","payment_terms","line_items"]'::jsonb,
    1,
    true
),
(
    'resume',
    'Resume Screener',
    'Extract candidate info, skills, experience, education from resumes/CVs.',
    'user',
    'hr',
    'Extract structured candidate information from these resumes. Capture all work experience entries and education details. List technical skills separately from soft skills.',
    '["full_name","email","phone","location","linkedin_url","years_of_experience","current_title","current_company","technical_skills","soft_skills","work_experience","education","certifications"]'::jsonb,
    'For work_experience, return array of objects: {company, title, start_date, end_date, description}. end_date should be ''Present'' if currently employed. years_of_experience should be a number calculated from earliest work start date. technical_skills and soft_skills should be arrays of strings. certifications should be an array of strings.',
    '[{"field":"years_of_experience","operator":"gte","value":5,"flag_name":"senior_candidate"}]'::jsonb,
    'json',
    '["processor.text_extract","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["full_name","email","phone","location","linkedin_url","years_of_experience","current_title","current_company","technical_skills","soft_skills","work_experience","education","certifications"]'::jsonb,
    2,
    true
),
(
    'contract',
    'Contract Analyzer',
    'Extract parties, dates, clauses, obligations from legal contracts.',
    'scale',
    'legal',
    'Analyze these legal contracts/agreements. Extract all parties, key dates, financial terms, and important clauses. Flag any auto-renewal or termination clauses.',
    '["contract_type","effective_date","expiration_date","party_a_name","party_a_role","party_b_name","party_b_role","contract_value","payment_schedule","auto_renewal","termination_notice_days","governing_law","key_obligations","confidentiality_clause","non_compete_clause","liability_cap"]'::jsonb,
    'contract_type examples: ''NDA'', ''MSA'', ''SaaS Agreement'', ''Employment Contract'', ''Lease''. auto_renewal should be true/false. key_obligations should be a short array of the most important obligations. confidentiality_clause and non_compete_clause should be true/false (whether they exist in the contract). liability_cap should be the dollar/currency amount if specified, else null.',
    '[{"field":"auto_renewal","operator":"eq","value":true,"flag_name":"has_auto_renewal"}]'::jsonb,
    'json',
    '["processor.text_extract","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["contract_type","effective_date","expiration_date","party_a_name","party_a_role","party_b_name","party_b_role","contract_value","payment_schedule","auto_renewal","termination_notice_days","governing_law","key_obligations","confidentiality_clause","non_compete_clause","liability_cap"]'::jsonb,
    3,
    true
),
(
    'receipt',
    'Receipt Scanner',
    'Extract merchant, total, tax, items from receipts for expense reports.',
    'credit-card',
    'finance',
    'Extract expense data from these receipts. Capture merchant name, total, tax, payment method, and line items.',
    '["merchant_name","merchant_address","receipt_date","receipt_number","subtotal","tax_amount","tip_amount","total_amount","payment_method","card_last_four","line_items","expense_category"]'::jsonb,
    'For line_items, return array of {item, quantity, price}. expense_category should be one of: meals, travel, office_supplies, software, equipment, entertainment, utilities, other. Infer category from merchant name and items. If tip is not present, set tip_amount to 0.',
    '[{"field":"total_amount","operator":"gt","value":5000,"flag_name":"needs_approval"}]'::jsonb,
    'csv',
    '["processor.ocr","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["merchant_name","merchant_address","receipt_date","receipt_number","subtotal","tax_amount","tip_amount","total_amount","payment_method","card_last_four","line_items","expense_category"]'::jsonb,
    4,
    true
),
(
    'purchase_order',
    'Purchase Order Extractor',
    'Extract PO details, line items, shipping info from purchase orders.',
    'package',
    'finance',
    'Extract purchase order data. Capture PO number, vendor, ship-to, all line items with SKU/quantity/price.',
    '["po_number","po_date","vendor_name","vendor_contact","ship_to_name","ship_to_address","line_items","subtotal","shipping_cost","tax","grand_total","delivery_date","payment_terms"]'::jsonb,
    'For line_items, return array of {sku, description, quantity, unit_price, total}. If SKU is not present, use ''N/A''. shipping_cost should be 0 if free shipping.',
    '[{"field":"grand_total","operator":"gt","value":100000,"flag_name":"large_order"}]'::jsonb,
    'csv',
    '["processor.ocr","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["po_number","po_date","vendor_name","vendor_contact","ship_to_name","ship_to_address","line_items","subtotal","shipping_cost","tax","grand_total","delivery_date","payment_terms"]'::jsonb,
    5,
    true
),
(
    'lease',
    'Lease Analyzer',
    'Extract rent, terms, clauses from property leases and rental agreements.',
    'home',
    'real_estate',
    'Analyze these property lease/rental agreements. Extract all financial terms, dates, and important clauses.',
    '["property_address","property_type","landlord_name","tenant_name","lease_start_date","lease_end_date","lease_duration_months","monthly_rent","security_deposit","currency","rent_escalation","late_fee","utilities_included","maintenance_responsibility","pet_policy","subletting_allowed","early_termination_fee","renewal_terms"]'::jsonb,
    'property_type: ''residential'', ''commercial'', ''industrial''. rent_escalation: annual percentage increase if mentioned, else null. utilities_included: array of strings like [''water'', ''electricity''] or empty array. maintenance_responsibility: ''landlord'', ''tenant'', or ''shared''. pet_policy: ''allowed'', ''not_allowed'', ''allowed_with_deposit''. subletting_allowed: true/false.',
    '[{"field":"monthly_rent","operator":"gt","value":100000,"flag_name":"high_rent"}]'::jsonb,
    'json',
    '["processor.text_extract","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["property_address","property_type","landlord_name","tenant_name","lease_start_date","lease_end_date","lease_duration_months","monthly_rent","security_deposit","currency","rent_escalation","late_fee","utilities_included","maintenance_responsibility","pet_policy","subletting_allowed","early_termination_fee","renewal_terms"]'::jsonb,
    6,
    true
),
(
    'medical_bill',
    'Medical Bill Parser',
    'Extract charges, procedure codes, insurance info from medical bills/EOBs.',
    'heart-pulse',
    'medical',
    'Extract billing data from these medical bills or Explanation of Benefits (EOB). Capture procedure codes, charges, insurance coverage, and patient responsibility.',
    '["patient_name","patient_id","date_of_service","provider_name","provider_npi","insurance_name","insurance_id","procedures","total_charges","total_insurance_paid","total_patient_responsibility","deductible_remaining"]'::jsonb,
    'For procedures, return array of: {cpt_code, description, charge, allowed, insurance_paid, patient_owes}. cpt_code is the 5-digit procedure code (e.g., 99213). If EOB, ''allowed'' is the insurance-approved amount. patient_owes = charge - insurance_paid (or as stated on the bill).',
    '[{"field":"total_patient_responsibility","operator":"gt","value":1000,"flag_name":"high_patient_cost"}]'::jsonb,
    'csv',
    '["processor.ocr","transform.field_extractor","transform.rules","output.formatter"]'::jsonb,
    '["patient_name","patient_id","date_of_service","provider_name","provider_npi","insurance_name","insurance_id","procedures","total_charges","total_insurance_paid","total_patient_responsibility","deductible_remaining"]'::jsonb,
    7,
    true
)
on conflict (id) do update set
    name = excluded.name,
    description = excluded.description,
    icon = excluded.icon,
    category = excluded.category,
    default_task = excluded.default_task,
    fields = excluded.fields,
    extraction_instructions = excluded.extraction_instructions,
    rules = excluded.rules,
    output_format = excluded.output_format,
    suggested_steps = excluded.suggested_steps,
    example_output_fields = excluded.example_output_fields,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();
